export const SELECT_TRACK = "SELECT_TRACK";

export const GET_TRACK_REQUEST = "GET_TRACK_REQUEST";
export const GET_TRACK_REQUEST_SUCCESS = "GET_TRACK_REQUEST_SUCCESS";
export const GET_TRACK_REQUEST_FAIL = "GET_TRACK_REQUEST_FAIL";


