export const ADD_TRACK = "ADD_TRACK";
export const DELETE_TRACK = "DELTETE_TRACK";
export const FIND_TRACK = "FIND_TRACK";

export const GET_TRACK_REQUEST = "GET_TRACK_REQUEST";
export const GET_TRACK_REQUEST_SUCCESS = "GET_TRACK_REQUEST_SUCCESS";
export const GET_TRACK_REQUEST_FAIL = "GET_TRACK_REQUEST_FAIL";

export const ADD_PLAYLIST = "ADD_PLAYLIST";
export const DELETE_PLAYLIST = "DELETE_PLAYLIST";
